# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gi < Formula
  desc "A simple interactive CLI tool to create a gitignore."
  homepage "https://github.com/uu64/gi"
  version "0.3.2"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/uu64/gi/releases/download/v0.3.2/gi_darwin_x86_64.tar.gz"
    sha256 "c07b9aa5e215f05b8c2d034b2023b26fbd61e6b0f82f69153e774c2dc6c8aaa2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/uu64/gi/releases/download/v0.3.2/gi_linux_x86_64.tar.gz"
    sha256 "dec476df19d652f4b1e364a89213a4a7548605e961fab5fc6d50504bfd12fa4e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/uu64/gi/releases/download/v0.3.2/gi_linux_arm64.tar.gz"
    sha256 "c5b628e73510ce74fc83c1107b4d1ca1e2778849a33e6ee955037fad1942f10f"
  end

  def install
    bin.install "gi"
  end

  test do
    system "#{bin}/gi", "--version"
  end
end
