# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gi < Formula
  desc "A simple interactive CLI tool to create a gitignore."
  homepage "https://github.com/uu64/gi"
  version "0.3.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/uu64/gi/releases/download/v0.3.1/gi_darwin_x86_64.tar.gz"
    sha256 "437c70593742d386dd032110d9e944f5f042236cdb2770186c15751ebfedf3bb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/uu64/gi/releases/download/v0.3.1/gi_linux_x86_64.tar.gz"
    sha256 "28b52f278764302dcf3380124ef4b27396a9a769c97303091ef3a15719099894"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/uu64/gi/releases/download/v0.3.1/gi_linux_arm64.tar.gz"
    sha256 "ae482cf725758dc12ce93f859152285a031214870cd502436215d1d068282146"
  end

  def install
    bin.install "gi"
  end

  test do
    system "#{bin}/gi", "--version"
  end
end
